import matter from 'gray-matter';
import { GuideConfig, ParsedGuide } from './types';

export class MarkdownParser {
  static parse(markdown: string): ParsedGuide {
    const { data, content } = matter(markdown);
    
    const frontmatter = data as GuideConfig;
    
    if (!frontmatter.title) {
      throw new Error('Missing required field: title');
    }
    
    if (!frontmatter.baseUrl) {
      throw new Error('Missing required field: baseUrl');
    }
    
    if (!frontmatter.steps || !Array.isArray(frontmatter.steps)) {
      throw new Error('Missing required field: steps (must be an array)');
    }

    return {
      frontmatter,
      body: content
    };
  }

  static hasPlaceholder(body: string): boolean {
    return body.includes('<!-- STEPS:AUTOGENERATED -->');
  }
}